var guns = [
	'M870 - 4 shell tube - buckshot',
	'M870 - 5 shell tube - buckshot',
	'M870 - 6 shell tube - buckshot',
	'M870 - 7 shell tube - buckshot',
	'M870 - 8 shell tube - buckshot',
	'M870 - 10 shell tube - buckshot',
	'M870 - 4 shell tube - slugs',
	'M870 - 5 shell tube - slugs',
	'M870 - 6 shell tube - slugs',
	'M870 - 7 shell tube - slugs',
	'M870 - 8 shell tube - slugs',
	'M870 - 10 shell tube - slugs',
	'MP153 - 4 shell tube -  buckshot',
	'MP153 - 5 shell tube - buckshot',
	'MP153 - 6 shell tube - buckshot',
	'MP153 - 7 shell tube - buckshot',
	'MP153 - 8 shell tube - buckshot',
	'MP153 - 10 shell tube - buckshot',
	'MP153 - 4 shell tube - slugs',
	'MP153 - 5 shell tube - slugs',
	'MP153 - 6 shell tube - slugs',
	'MP153 - 7 shell tube - slugs',
	'MP153 - 8 shell tube - slugs',
	'MP153 - 10 shell tube - slugs',
	'MP133 - 4 shell tube -  buckshot',
	'MP133 - 5 shell tube - buckshot',
	'MP133 - 6 shell tube - buckshot',
	'MP133 - 7 shell tube - buckshot',
	'MP133 - 8 shell tube - buckshot',
	'MP133 - 10 shell tube - buckshot',
	'MP133 - 4 shell tube - slugs',
	'MP133 - 5 shell tube - slugs',
	'MP133 - 6 shell tube - slugs',
	'MP133 - 7 shell tube - slugs',
	'MP133 - 8 shell tube - slugs',
	'MP133 - 10 shell tube - slugs',
	'Saiga-12 - 10 rounders - buckshot',
	'Saiga-12 - 5 rounders - buckshot',
	'Saiga-12 - 10 rounders - slugs',
	'Saiga-12 - 5 rounders - slugs',
	'Vepr-209 - 10 rounder',
	'Vepr-209 - 10 rounder',
	'Vepr-209 - 30 rounder',
	'Vepr-209 - 30 rounder',
	'Vepr-209 - 40 rounder',
	'Vepr-209 - 40 rounder',
	'TOZ / ReRoll',
	'AK-103 short - 10 rounders',
	'AK-103 long - 10 rounders',
	'AK-103 short - 30 rounders',
	'AK-103 long - 30 rounders',
	'AK-103 short - 30 rounders',
	'AK-103 long - 30 rounders',
	'AK-103 short - 30 rounders',
	'AK-103 long - 30 rounders',
	'AK-103 long - 40/45 rounders',
	'AK-103 short - 40/45 rounders',
	'AK-104 short - 10 rounders',
	'AK-104 long - 10 rounders',
	'AK-104 short - 30 rounders',
	'AK-104 long - 30 rounders',
	'AK-104 short - 30 rounders',
	'AK-104 long - 30 rounders',
	'AK-104 short - 30 rounders',
	'AK-104 long - 30 rounders',
	'AK-104 long - 40/45 rounders',
	'AK-104 short - 40/45 rounders',
	'M4A1 - 10 rounders',
	'M4A1 - 20 rounders',
	'M4A1 - 20 rounders',
	'M4A1 - 30 rounders',
	'M4A1 - 30 rounders',
	'M4A1 - 40/50 rounders',
	'HK-416 - 10 rounders',
	'HK-416 - 20 rounders',
	'HK-416 - 20 rounders',
	'HK-416 - 30 rounders',
	'HK-416 - 30 rounders',
	'HK-416 - 40/50 rounders',
	'SA-58 - 10 rounders',
	'SA-58 - 20 rounders',
	'SA-58 - 20 rounders',
	'SA-58 - 30 rounders',
	'SA-58 - 30 rounders',
	'SA-58 - 40/50 rounders',
	'VAL/VSS - 10 rounders',
	'VAL/VSS -  20 rounders',
	'VAL/VSS -  20 rounders',
	'VAL/VSS -  20 rounders',
	'VAL/VSS -  20 rounders',
	'VAL/VSS - 30 rounders',
	'PP-19 - 10 rounders',
	'PP-19 - 20 rounders',
	'PP-19 - 20 rounders',
	'PP-19 - 30 rounders',
	'PP-19 - 30 rounders',
	'PP-19 - 30 rounders',
	'Kedr - 20 rounders',
	'Kedr - 20 rounders',
	'Kedr - 20 rounders',
	'Kedr - 30 rounders',
	'Kedr - 30 rounders',
	'Kedr - 30 rounders',
	'MPX',
	'MP7 - 20 rounders',
	'MP7 - 30 rounders',
	'MP7 - 30 rounders',
	'MP7 - 30 rounders',
	'MP7 - 30 rounders',
	'MP7 - 40 rounders',
	'MP5 - 30 rounders',
	'MP5 - 30 rounders',
	'MP5 - 30 rounders',
	'MP5 - 30 rounders',
	'MP5 - 50 rounders',
	'MP5 - 50 rounders',
	'G18  - 17 rounders',
	'G18  - 17 rounders',
	'G18  - 17 rounders',
	'G18  - 21 rounders',
	'G18  - 21 rounders',
	'G18  - 33 rounders',
	'G18  - 33 rounders',
	'G18  - 21 rounders',
	'G18  - 21 rounders',
	'G18  - 33 rounders',
	'G18  - 33 rounders',
	'G18  - 50 rounders',
	'APS - No Stock',
	'APS - No Stock',
	'APS - No Stock',
	'APS - No Stock',
	'APS - No Stock',
	'APS - No Stock',
	'APS - With Stock',
	'APS - With Stock',
	'APS - With Stock',
	'APS - With Stock',
	'APS - With Stock',
	'APS - With Stock',
	'M1A - Socom Short- 20 rounders',
	'M1A - Socom Short - 20 rounders',
	'M1A - Socom Short - 20 rounders',
	'M1A - Socom Short - 20 rounders',
	'M1A - Socom Short - 30 rounders',
	'M1A - Socom Short - 30 rounders',
	'M1A - Socom Short - 30 rounders',
	'M1A - Socom Short - 30 rounders',
	'M1A - Socom Short - 30 rounders',
	'M1A - Socom Short - 50 rounders',
	'M1A - EBR Short - 20 rounders',
	'M1A - EBR Short - 20 rounders',
	'M1A - EBR Short - 20 rounders',
	'M1A - EBR Short - 20 rounders',
	'M1A - EBR Short - 30 rounders',
	'M1A - EBR Short - 30 rounders',
	'M1A - EBR Short - 30 rounders',
	'M1A - EBR Short - 30 rounders',
	'M1A - EBR Short - 30 rounders',
	'M1A - EBR Short - 50 rounders',
	'M1A - SASS Short - 20 rounders',
	'M1A - SASS Short - 20 rounders',
	'M1A - SASS Short - 20 rounders',
	'M1A - SASS Short - 20 rounders',
	'M1A - SASS Short - 30 rounders',
	'M1A - SASS Short - 30 rounders',
	'M1A - SASS Short - 30 rounders',
	'M1A - SASS Short - 30 rounders',
	'M1A - SASS Short - 30 rounders',
	'M1A - SASS Short - 50 rounders',
	'M1A - Socom Long- 20 rounders',
	'M1A - Socom Long - 20 rounders',
	'M1A - Socom Long - 20 rounders',
	'M1A - Socom Long - 20 rounders',
	'M1A - Socom Long - 30 rounders',
	'M1A - Socom Long - 30 rounders',
	'M1A - Socom Long - 30 rounders',
	'M1A - Socom Long - 30 rounders',
	'M1A - Socom Long - 30 rounders',
	'M1A - Socom Long - 50 rounders',
	'M1A - EBR Long - 20 rounders',
	'M1A - EBR Long - 20 rounders',
	'M1A - EBR Long - 20 rounders',
	'M1A - EBR Long - 20 rounders',
	'M1A - EBR Long - 30 rounders',
	'M1A - EBR Long - 30 rounders',
	'M1A - EBR Long - 30 rounders',
	'M1A - EBR Long - 30 rounders',
	'M1A - EBR Long - 30 rounders',
	'M1A - EBR Long - 50 rounders',
	'M1A - SASS Long - 20 rounders',
	'M1A - SASS Long - 20 rounders',
	'M1A - SASS Long - 20 rounders',
	'M1A - SASS Long - 20 rounders',
	'M1A - SASS Long - 30 rounders',
	'M1A - SASS Long - 30 rounders',
	'M1A - SASS Long - 30 rounders',
	'M1A - SASS Long - 30 rounders',
	'M1A - SASS Long - 30 rounders',
	'M1A - SASS Long - 50 rounders',
	'RSASS - Short',
	'RSASS - Short',
	'RSASS - Short',
	'RSASS - Short',
	'RSASS - Short',
	'RSASS - Short',
	'RSASS - Long',
	'RSASS - Long',
	'RSASS - Long',
	'RSASS - Long',
	'RSASS - Long',
	'RSASS - Long',
	'Vepr-136 - 10 rounders',
	'Vepr-136 - 10 rounders',
	'Vepr-136 - 30 rounders',
	'Vepr-136 - 30 rounders',
	'Vepr-136 - 40/45 rounders',
	'Vepr-136 - 40/45 rounders',
	'AK-74 locked to semi-auto - 10 rounders',
	'AK-74 locked to semi-auto - 10 rounders',
	'AK-74 locked to semi-auto - 30 rounders',
	'AK-74 locked to semi-auto - 30 rounders',
	'AK-74 locked to semi-auto - 40/45 rounders',
	'AK-74 locked to semi-auto - 40/45 rounders',
	'AR-15 Short - 10 rounders',
	'AR-15 Short - 20 rounders',
	'AR-15 Short - 20 rounders',
	'AR-15 Short - 30 rounders',
	'AR-15 Short - 30 rounders',
	'AR-15 Short - 40 rounders',
	'AR-15 Long - 10 rounders',
	'AR-15 Long - 20 rounders',
	'AR-15 Long - 20 rounders',
	'AR-15 Long - 30 rounders',
	'AR-15 Long - 30 rounders',
	'AR-15 Long - 40 rounders',
	'SKS',
	'Saiga-9 - 10 rounders',
	'Saiga-9 - 20 rounders',
	'Saiga-9 - 20 rounders',
	'Saiga-9 - 30 rounders',
	'Saiga-9 - 30 rounders',
	'Mosin',
	'R700',
	'SV-98',
	'DVL',
	'Short Mosin',
	'DVL Saboteur',
]

var magnification = [
	'1x',
	'1x',
	'1x',
	'Magnified',
	'Magnified',
	'Magnified',
]

var onexoptics = [
	'Iron',
	'Red Dot',
	'Red Dot',
	'Holo Sights',
	'Holo Sights',
	'Scar Sights',
]

var magoptics = [
	'2.5x Billy Sight',
	'4x Locked',
	'4x Locked',
	'4x Locked',
	'6x Locked',
	'8x+ Locked',
]

var suppress = [
	'Suppressed if applicable',
	'Suppressed if applicable',
	'Suppressed if applicable',
	'Loud if applicable',
	'Loud if applicable',
	'Loud if applicable',
]

var sidearm = [
	'Makarov',
	'P226R',
	'G17 (Stock Mags)',
	'TT',
	'Grach',
	'3 Slot M870 or 3 Slot Mosin'
]

var raid = [
	'Woods',
	'Customs',
	'Shoreline',
	'Interchange',
	'Labs',
	'Custom Quest',
]

var raidquests = [
	'Kill 3 players (including player Scavs) or kill 1 player more than 200m away.',
	'Adopt a player and have him/her extract or kill a player using a grenade.',
	'Extract with 4 sets of clothing. 1 clothing set = 1 hat + 1 face + 1 eyeware. Clothing such as a gas mask counts as 1 set.',
	'Extract with a bag of ammo. For Labs, Woods and Customs you must fill a 3x3 area with full stacks. For Shoreline and Interchange you must fill a 4x4 area with full stacks.',
	'Extract with 6 new and different guns.',
	'Extract with 4 meals. 1 meal = 1 food + 1 drink.',
]

var customquest = [
	'Woods:   It gets lonely in Tarkov. Your mission is to find a twink or BEAR to spend your glory days with. Find a life partner (hatchling, player scav, statue or Vaseline) and find 2 meals (1 food and 1 drink each). Bring them to the Scav House where you will have dinner together. You will then consummate your love to completet the quest (open to interpretation).',
	'Shoreline:   Astronomy and anime is all you have left after Tarkov fell. Visit East 206 and West 303 to acquire the gyroscope and projector respectively. You will then visit the unlocked luxury house to get your body pillow, the locked luxury house to get the neighbours telescope and the general store in town to get some DVDs. Take everything back to the top of the observatory tower to enjoy and evening of hentai with senpai ending with a night watching the stars. Doing so completes the quest.',
	'Customs:   It is your turn with the slag in 206. Find a 206 key in raid and swing by a gas station to pick up some beers. Then go to dorm room 206 to complete the quest.',
	'Interchange:   You have to acquire a date (hatchling, statue or vaseline), pick up 2 meals (1 food and 1 drink each), then go to the band room in the upstairs book store. Then take him/her to the backroom of the coat drop off in IDEA for a shagging to complete the quest.',
	'Labs:   You have developed a crippling drug addiction. Acquire 4 drugs and slam them all at once, then go on a rampage for the duration of the effects. Once you are done go to the bathroom to wash your face and decide it is time to get back on track. Go to the gym to get your body healthy then extract to begin the journey of getting your mind healthy. Doing so completes the quest.',
	'Shoreline:   Drug Addiction Part 2 Electric Boogaloo. Your spiritual journey has begun, visit the general store to get some kale and vitamin water, notice a flyer for a spiritual awakening seminar for the church in the swamp and go there. Notice no one is there then decide to have a more calculated approach. Go to the Health Resort and visit the doctor in West 104 to complete the quest. If you find any drugs along the way, give in to temptation and slam them. Then go on a murderous rampage for the duration of the effects, slamming any other drugs you find along the way. Once they expire, realise you were never in control of your life, go to the top of the lighthouse tower to commit suicide while overlooking the water to complete the quest.',
]

function newRoll() {

	var randomGun = Math.floor(Math.random() * (guns.length));
	document.getElementById('gunDisplay').innerHTML = guns[randomGun];
	var randomMag = Math.floor(Math.random() * (magnification.length));
	document.getElementById('magDisplay').innerHTML = magnification[randomMag];
	var randomOnex = Math.floor(Math.random() * (onexoptics.length));
	document.getElementById('onexDisplay').innerHTML = onexoptics[randomOnex];
	var randomOptics = Math.floor(Math.random() * (magoptics.length));
	document.getElementById('magnifiedDisplay').innerHTML = magoptics[randomOptics];
	var randomSuppress = Math.floor(Math.random() * (suppress.length));
	document.getElementById('suppressDisplay').innerHTML = suppress[randomSuppress];
	var randomSidearm = Math.floor(Math.random() * (sidearm.length));
	document.getElementById('sidearmDisplay').innerHTML = sidearm[randomSidearm];
	var randomRaid = Math.floor(Math.random() * (raid.length));
	document.getElementById('raidDisplay').innerHTML = raid[randomRaid];
	var randomRaidqu = Math.floor(Math.random() * (raidquests.length));
	document.getElementById('raidqDisplay').innerHTML = raidquests[randomRaidqu];
	var randomCustomqu = Math.floor(Math.random() * (customquest.length));
	document.getElementById('customqDisplay').innerHTML = customquest[randomCustomqu];

	if (document.getElementById('magDisplay').innerHTML === '1x') {
		document.getElementById('onexDisplay').style.display = 'inline';
		document.getElementById('magnifiedDisplay').style.display = 'none';
	} else {
		document.getElementById('magnifiedDisplay').style.display = 'inline';
		document.getElementById('onexDisplay').style.display = 'none';
	}
	
	if (document.getElementById('raidDisplay').innerHTML ==='Custom Quest') {
		document.getElementById('customqDisplay').style.display = 'block';
		document.getElementById('raidqDisplay').style.display = 'none';
	} else {
		document.getElementById('customqDisplay').style.display = 'none';
		document.getElementById('raidqDisplay').style.display = 'inline';
	}
	
}

function reloadPg() {
	location.reload();
}
